//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Packages/com.seed.unity/Runtime/Input/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Seed.Unity.Input
{
    public partial class @InputActions : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @InputActions()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""Menu"",
            ""id"": ""60376cc8-c714-4b3c-92fb-0ac588375532"",
            ""actions"": [
                {
                    ""name"": ""North"",
                    ""type"": ""Button"",
                    ""id"": ""21e1b2d6-34e6-488a-ae5e-1287790d4cfa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""East"",
                    ""type"": ""Button"",
                    ""id"": ""c25739bb-fa60-4a54-ad5a-237e57b11ad0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""South"",
                    ""type"": ""Button"",
                    ""id"": ""12ba176d-63d1-4d8a-a12b-e5dd6d4007ce"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""West"",
                    ""type"": ""Button"",
                    ""id"": ""202710de-341b-48bf-88dd-c01f5fe4da0d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftStickMove"",
                    ""type"": ""Value"",
                    ""id"": ""e01c97e4-794a-4cee-bf93-fe33e5863f8a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftStickPress"",
                    ""type"": ""Button"",
                    ""id"": ""03ee0bba-6427-4934-8ae6-1e1bbecb599a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightStickMove"",
                    ""type"": ""Value"",
                    ""id"": ""923e4b90-8ee6-4aff-9506-133c4ba33917"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightStickPress"",
                    ""type"": ""Button"",
                    ""id"": ""8887ac65-d6a2-4933-a573-b060735ae1de"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DPadMove"",
                    ""type"": ""Value"",
                    ""id"": ""5a72ffe5-8644-489a-b41f-676a446ee4c0"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Start"",
                    ""type"": ""Button"",
                    ""id"": ""8023a7d5-ccf6-4b21-a27a-a2695b57150d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""919a2265-b179-4ac6-b6bf-3676eb80d0c7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftTrigger"",
                    ""type"": ""Button"",
                    ""id"": ""24a0af17-e4d0-4343-a011-67a462f283f6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightTrigger"",
                    ""type"": ""Button"",
                    ""id"": ""a28a285e-e8f7-47df-96b1-30da09f539b1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftShoulder"",
                    ""type"": ""Button"",
                    ""id"": ""61b8448f-45bd-40d6-9178-804e96e85a20"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightShoulder"",
                    ""type"": ""Button"",
                    ""id"": ""7e251e13-9729-438a-a8d8-0cdf63bb1e09"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9d0414e1-b0d8-4254-bfa5-ea8a08d2d844"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""North"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e6b5eb5f-c444-4f93-a614-198a30d95fc4"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""North"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4efdcbcf-3110-44f0-9689-5afd6bcb9b33"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""East"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""df40a69d-5735-463d-abe1-cbec0e631b9f"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""East"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7d900884-5db3-4bb5-86d3-96063f7304dd"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""South"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""45f24aa2-330b-45f3-8bbb-bf7930594c18"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""South"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5bba0f8a-a057-4ff6-96ef-a7f60f1491ee"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""West"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""124cfeff-48c6-4ae0-a918-ed592085d9fe"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""West"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""31fef19f-660b-40af-ab68-b3f9080f6778"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""87b38f5b-07b2-40fa-985d-7d9b371e81c4"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""bb15fd9a-2618-4ad3-bf2b-d11ae2c5817b"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""9eb86e3a-8231-4e40-9eb8-461c2fc7a7a9"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""88cccdcb-8faf-40a5-b3d3-d6dd3c9ea323"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b28c2512-cbb8-45c2-9119-b582d014a75d"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""78928742-0403-4eea-968b-307094ba3292"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStickMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c3ed6ad2-f2ba-42ad-b51e-60a799793526"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStickMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a26d026a-73b9-4305-903c-e6db02ba03eb"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DPadMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Arrows"",
                    ""id"": ""3d84f456-9f0d-4631-8cd8-8c068122114e"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DPadMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""6f1224c3-e1e6-4b74-950a-eb98175ac4f2"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DPadMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""57cb9544-9bb0-4a08-869f-5f2be006b530"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DPadMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""6458eb29-efc8-4955-8e33-34bf6b7d6647"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DPadMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""6930b5e1-8b01-43cf-a6f6-e12df6e420d5"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DPadMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""28376f10-ce64-412f-959d-ae3407a26d4a"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1db6e673-feec-4e6a-8490-3f362b79c0c4"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""91a4a57c-cc35-4ac0-9d05-42971b201d3e"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStickPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6e76084a-a755-4af7-949b-77ced305c854"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f5340be0-62e2-425b-98f3-917ab6e00fa7"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""21dbf58b-2a3c-4893-932f-41d07d75a963"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""76a8900f-217b-4b28-aa2c-293984e5b21d"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b0042284-f1d4-405a-a281-d08c5166b5eb"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4fd3f382-48c6-451e-bd38-4882517ff056"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""18c7a9f5-6633-41e4-a0e5-4c375422f4be"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5dcc27be-35d2-41ae-a43f-c159b0bda38d"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9b45fcb1-a150-425e-a2fa-2fa060e01fb1"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftShoulder"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""acddf527-cb53-43af-b1ad-8c147da6b01b"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftShoulder"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7f2e84d6-84f8-4f1e-8188-4234ce4a5f16"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightShoulder"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""992db276-274d-4290-b05d-991364e07f0b"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightShoulder"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Player"",
            ""id"": ""1207ca70-9b97-48bb-b8b0-d44ba7fa8419"",
            ""actions"": [
                {
                    ""name"": ""North"",
                    ""type"": ""Button"",
                    ""id"": ""77416f35-55fd-4e2b-9cb2-d094ce750322"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""East"",
                    ""type"": ""Button"",
                    ""id"": ""52d5db5f-72d6-4afb-ac06-6231b12eb4f1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""South"",
                    ""type"": ""Button"",
                    ""id"": ""9a4a9c20-7c0f-4a22-b0f7-376c2537fd22"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""West"",
                    ""type"": ""Button"",
                    ""id"": ""0db9eaa7-9792-4ad4-8473-fb9fc7e4b389"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftStickMove"",
                    ""type"": ""Value"",
                    ""id"": ""2aa8c2b6-5eae-4c61-a802-fe329e8361bf"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftStickPress"",
                    ""type"": ""Button"",
                    ""id"": ""8a645b21-ef65-4c04-bf17-8dc5e167a880"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightStickMove"",
                    ""type"": ""Value"",
                    ""id"": ""678ccf7e-197a-466f-858c-fb99ea5ea018"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightStickPress"",
                    ""type"": ""Button"",
                    ""id"": ""19b7f683-f74f-4d11-ba05-ba8a15db4fa7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DPadMove"",
                    ""type"": ""Value"",
                    ""id"": ""dc547d8b-4c5b-4e14-a25b-106dd3a7a6e0"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Start"",
                    ""type"": ""Button"",
                    ""id"": ""7240dcd3-8f4c-4ac8-8cf4-66c6a7f8a820"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""00b157f5-3d0f-4d8b-9cec-894d33eeed54"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftTrigger"",
                    ""type"": ""Button"",
                    ""id"": ""371763b8-2674-4aab-8707-1c7b6346d714"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightTrigger"",
                    ""type"": ""Button"",
                    ""id"": ""93ad83ad-36fe-4f67-9feb-9060a26621ee"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftShoulder"",
                    ""type"": ""Button"",
                    ""id"": ""c6b3cf2c-c011-4752-9b6b-b4559a346da2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightShoulder"",
                    ""type"": ""Button"",
                    ""id"": ""3e70c46b-616d-40b3-be26-8d8c19140e30"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1d8f2419-2ba7-4a07-9a4f-dc1d9c072a91"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""North"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""183241fd-9ea1-4d35-bb7a-c65213514747"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""North"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d8a322e6-e318-4278-bc03-d95e06770d68"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""East"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6cc4e774-b3b7-4195-b2e0-d226b9499c57"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""East"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""edab7af7-032c-43dd-a733-20aa9ebaaee0"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""South"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ace13f52-296c-4a22-95c7-6d7c99304218"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""South"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f33856d8-61a7-470e-bb9a-3da106fd4360"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""West"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3a980f22-b485-410f-865f-ddf9f6057a9a"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""West"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""533aa0b2-563b-4dff-8df1-4f5356ae3866"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""c9209c04-1606-4421-8321-90b7496307de"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d80ea131-ba20-40de-a2b3-9b69868bde41"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""1f4d70a1-b100-406c-991c-f7e1734f0898"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""13391b91-f23b-4b07-a38c-97b1f3a2d89d"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""e34d458c-6094-40b8-84d4-e6e7b9b15e64"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""acfc05ef-180e-4c72-aa15-212c5878da75"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStickMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3d71e465-02f6-4e42-ac3b-621ca5ff50f6"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStickMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""51fee785-8276-4380-b88f-147f5a2faf25"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DPadMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Arrows"",
                    ""id"": ""16afe1df-0a4f-442b-b211-f6efa9d33bbf"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DPadMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""7d2e55fd-ff57-47a0-b88d-5e222613db3c"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DPadMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""fa363461-f246-48f0-8bae-c87649c1e3bb"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DPadMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""b41ffa30-3c8d-4116-a303-fa4d7ab1922b"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DPadMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""12120ad2-3745-47c5-891f-699b29a8f3e3"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DPadMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""1a01dc6f-fc1e-45e4-b73c-f5dbad6080ec"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0d3a6f2b-a51c-4d8b-ab8a-9fa7657cfbe9"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""58bff8f2-d906-4529-8315-dc70f0d99c9e"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStickPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""41c5f6cf-23ca-48f2-a9d8-a94b4f7e23ff"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ca95d01d-afbe-4dfa-8863-a427e48f7d93"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5764fd80-75e6-4893-94c2-f1073d0cf6fe"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1ea7a517-a596-49e5-be72-0661160cb47b"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""73a08099-0bdc-4e29-a1b7-83f526d42970"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0927dbd1-a8d1-489d-a42b-08034672c8c0"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d775f9aa-76fc-481a-be2d-afd3dac708f5"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""92dcf5b6-d5de-4468-a8ad-8c873487106d"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""855bac33-dcb4-4c5a-98af-5e5cf93a43c5"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftShoulder"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bc785933-4021-4a93-8a07-657494cdd42d"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftShoulder"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""977f436d-d77a-4bd7-9eaa-db48a2f4f4ea"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightShoulder"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8ba27eae-fca2-424d-8124-a48fb6532d52"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightShoulder"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Menu
            m_Menu = asset.FindActionMap("Menu", throwIfNotFound: true);
            m_Menu_North = m_Menu.FindAction("North", throwIfNotFound: true);
            m_Menu_East = m_Menu.FindAction("East", throwIfNotFound: true);
            m_Menu_South = m_Menu.FindAction("South", throwIfNotFound: true);
            m_Menu_West = m_Menu.FindAction("West", throwIfNotFound: true);
            m_Menu_LeftStickMove = m_Menu.FindAction("LeftStickMove", throwIfNotFound: true);
            m_Menu_LeftStickPress = m_Menu.FindAction("LeftStickPress", throwIfNotFound: true);
            m_Menu_RightStickMove = m_Menu.FindAction("RightStickMove", throwIfNotFound: true);
            m_Menu_RightStickPress = m_Menu.FindAction("RightStickPress", throwIfNotFound: true);
            m_Menu_DPadMove = m_Menu.FindAction("DPadMove", throwIfNotFound: true);
            m_Menu_Start = m_Menu.FindAction("Start", throwIfNotFound: true);
            m_Menu_Select = m_Menu.FindAction("Select", throwIfNotFound: true);
            m_Menu_LeftTrigger = m_Menu.FindAction("LeftTrigger", throwIfNotFound: true);
            m_Menu_RightTrigger = m_Menu.FindAction("RightTrigger", throwIfNotFound: true);
            m_Menu_LeftShoulder = m_Menu.FindAction("LeftShoulder", throwIfNotFound: true);
            m_Menu_RightShoulder = m_Menu.FindAction("RightShoulder", throwIfNotFound: true);
            // Player
            m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
            m_Player_North = m_Player.FindAction("North", throwIfNotFound: true);
            m_Player_East = m_Player.FindAction("East", throwIfNotFound: true);
            m_Player_South = m_Player.FindAction("South", throwIfNotFound: true);
            m_Player_West = m_Player.FindAction("West", throwIfNotFound: true);
            m_Player_LeftStickMove = m_Player.FindAction("LeftStickMove", throwIfNotFound: true);
            m_Player_LeftStickPress = m_Player.FindAction("LeftStickPress", throwIfNotFound: true);
            m_Player_RightStickMove = m_Player.FindAction("RightStickMove", throwIfNotFound: true);
            m_Player_RightStickPress = m_Player.FindAction("RightStickPress", throwIfNotFound: true);
            m_Player_DPadMove = m_Player.FindAction("DPadMove", throwIfNotFound: true);
            m_Player_Start = m_Player.FindAction("Start", throwIfNotFound: true);
            m_Player_Select = m_Player.FindAction("Select", throwIfNotFound: true);
            m_Player_LeftTrigger = m_Player.FindAction("LeftTrigger", throwIfNotFound: true);
            m_Player_RightTrigger = m_Player.FindAction("RightTrigger", throwIfNotFound: true);
            m_Player_LeftShoulder = m_Player.FindAction("LeftShoulder", throwIfNotFound: true);
            m_Player_RightShoulder = m_Player.FindAction("RightShoulder", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Menu
        private readonly InputActionMap m_Menu;
        private IMenuActions m_MenuActionsCallbackInterface;
        private readonly InputAction m_Menu_North;
        private readonly InputAction m_Menu_East;
        private readonly InputAction m_Menu_South;
        private readonly InputAction m_Menu_West;
        private readonly InputAction m_Menu_LeftStickMove;
        private readonly InputAction m_Menu_LeftStickPress;
        private readonly InputAction m_Menu_RightStickMove;
        private readonly InputAction m_Menu_RightStickPress;
        private readonly InputAction m_Menu_DPadMove;
        private readonly InputAction m_Menu_Start;
        private readonly InputAction m_Menu_Select;
        private readonly InputAction m_Menu_LeftTrigger;
        private readonly InputAction m_Menu_RightTrigger;
        private readonly InputAction m_Menu_LeftShoulder;
        private readonly InputAction m_Menu_RightShoulder;
        public struct MenuActions
        {
            private @InputActions m_Wrapper;
            public MenuActions(@InputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @North => m_Wrapper.m_Menu_North;
            public InputAction @East => m_Wrapper.m_Menu_East;
            public InputAction @South => m_Wrapper.m_Menu_South;
            public InputAction @West => m_Wrapper.m_Menu_West;
            public InputAction @LeftStickMove => m_Wrapper.m_Menu_LeftStickMove;
            public InputAction @LeftStickPress => m_Wrapper.m_Menu_LeftStickPress;
            public InputAction @RightStickMove => m_Wrapper.m_Menu_RightStickMove;
            public InputAction @RightStickPress => m_Wrapper.m_Menu_RightStickPress;
            public InputAction @DPadMove => m_Wrapper.m_Menu_DPadMove;
            public InputAction @Start => m_Wrapper.m_Menu_Start;
            public InputAction @Select => m_Wrapper.m_Menu_Select;
            public InputAction @LeftTrigger => m_Wrapper.m_Menu_LeftTrigger;
            public InputAction @RightTrigger => m_Wrapper.m_Menu_RightTrigger;
            public InputAction @LeftShoulder => m_Wrapper.m_Menu_LeftShoulder;
            public InputAction @RightShoulder => m_Wrapper.m_Menu_RightShoulder;
            public InputActionMap Get() { return m_Wrapper.m_Menu; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(MenuActions set) { return set.Get(); }
            public void SetCallbacks(IMenuActions instance)
            {
                if (m_Wrapper.m_MenuActionsCallbackInterface != null)
                {
                    @North.started -= m_Wrapper.m_MenuActionsCallbackInterface.OnNorth;
                    @North.performed -= m_Wrapper.m_MenuActionsCallbackInterface.OnNorth;
                    @North.canceled -= m_Wrapper.m_MenuActionsCallbackInterface.OnNorth;
                    @East.started -= m_Wrapper.m_MenuActionsCallbackInterface.OnEast;
                    @East.performed -= m_Wrapper.m_MenuActionsCallbackInterface.OnEast;
                    @East.canceled -= m_Wrapper.m_MenuActionsCallbackInterface.OnEast;
                    @South.started -= m_Wrapper.m_MenuActionsCallbackInterface.OnSouth;
                    @South.performed -= m_Wrapper.m_MenuActionsCallbackInterface.OnSouth;
                    @South.canceled -= m_Wrapper.m_MenuActionsCallbackInterface.OnSouth;
                    @West.started -= m_Wrapper.m_MenuActionsCallbackInterface.OnWest;
                    @West.performed -= m_Wrapper.m_MenuActionsCallbackInterface.OnWest;
                    @West.canceled -= m_Wrapper.m_MenuActionsCallbackInterface.OnWest;
                    @LeftStickMove.started -= m_Wrapper.m_MenuActionsCallbackInterface.OnLeftStickMove;
                    @LeftStickMove.performed -= m_Wrapper.m_MenuActionsCallbackInterface.OnLeftStickMove;
                    @LeftStickMove.canceled -= m_Wrapper.m_MenuActionsCallbackInterface.OnLeftStickMove;
                    @LeftStickPress.started -= m_Wrapper.m_MenuActionsCallbackInterface.OnLeftStickPress;
                    @LeftStickPress.performed -= m_Wrapper.m_MenuActionsCallbackInterface.OnLeftStickPress;
                    @LeftStickPress.canceled -= m_Wrapper.m_MenuActionsCallbackInterface.OnLeftStickPress;
                    @RightStickMove.started -= m_Wrapper.m_MenuActionsCallbackInterface.OnRightStickMove;
                    @RightStickMove.performed -= m_Wrapper.m_MenuActionsCallbackInterface.OnRightStickMove;
                    @RightStickMove.canceled -= m_Wrapper.m_MenuActionsCallbackInterface.OnRightStickMove;
                    @RightStickPress.started -= m_Wrapper.m_MenuActionsCallbackInterface.OnRightStickPress;
                    @RightStickPress.performed -= m_Wrapper.m_MenuActionsCallbackInterface.OnRightStickPress;
                    @RightStickPress.canceled -= m_Wrapper.m_MenuActionsCallbackInterface.OnRightStickPress;
                    @DPadMove.started -= m_Wrapper.m_MenuActionsCallbackInterface.OnDPadMove;
                    @DPadMove.performed -= m_Wrapper.m_MenuActionsCallbackInterface.OnDPadMove;
                    @DPadMove.canceled -= m_Wrapper.m_MenuActionsCallbackInterface.OnDPadMove;
                    @Start.started -= m_Wrapper.m_MenuActionsCallbackInterface.OnStart;
                    @Start.performed -= m_Wrapper.m_MenuActionsCallbackInterface.OnStart;
                    @Start.canceled -= m_Wrapper.m_MenuActionsCallbackInterface.OnStart;
                    @Select.started -= m_Wrapper.m_MenuActionsCallbackInterface.OnSelect;
                    @Select.performed -= m_Wrapper.m_MenuActionsCallbackInterface.OnSelect;
                    @Select.canceled -= m_Wrapper.m_MenuActionsCallbackInterface.OnSelect;
                    @LeftTrigger.started -= m_Wrapper.m_MenuActionsCallbackInterface.OnLeftTrigger;
                    @LeftTrigger.performed -= m_Wrapper.m_MenuActionsCallbackInterface.OnLeftTrigger;
                    @LeftTrigger.canceled -= m_Wrapper.m_MenuActionsCallbackInterface.OnLeftTrigger;
                    @RightTrigger.started -= m_Wrapper.m_MenuActionsCallbackInterface.OnRightTrigger;
                    @RightTrigger.performed -= m_Wrapper.m_MenuActionsCallbackInterface.OnRightTrigger;
                    @RightTrigger.canceled -= m_Wrapper.m_MenuActionsCallbackInterface.OnRightTrigger;
                    @LeftShoulder.started -= m_Wrapper.m_MenuActionsCallbackInterface.OnLeftShoulder;
                    @LeftShoulder.performed -= m_Wrapper.m_MenuActionsCallbackInterface.OnLeftShoulder;
                    @LeftShoulder.canceled -= m_Wrapper.m_MenuActionsCallbackInterface.OnLeftShoulder;
                    @RightShoulder.started -= m_Wrapper.m_MenuActionsCallbackInterface.OnRightShoulder;
                    @RightShoulder.performed -= m_Wrapper.m_MenuActionsCallbackInterface.OnRightShoulder;
                    @RightShoulder.canceled -= m_Wrapper.m_MenuActionsCallbackInterface.OnRightShoulder;
                }
                m_Wrapper.m_MenuActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @North.started += instance.OnNorth;
                    @North.performed += instance.OnNorth;
                    @North.canceled += instance.OnNorth;
                    @East.started += instance.OnEast;
                    @East.performed += instance.OnEast;
                    @East.canceled += instance.OnEast;
                    @South.started += instance.OnSouth;
                    @South.performed += instance.OnSouth;
                    @South.canceled += instance.OnSouth;
                    @West.started += instance.OnWest;
                    @West.performed += instance.OnWest;
                    @West.canceled += instance.OnWest;
                    @LeftStickMove.started += instance.OnLeftStickMove;
                    @LeftStickMove.performed += instance.OnLeftStickMove;
                    @LeftStickMove.canceled += instance.OnLeftStickMove;
                    @LeftStickPress.started += instance.OnLeftStickPress;
                    @LeftStickPress.performed += instance.OnLeftStickPress;
                    @LeftStickPress.canceled += instance.OnLeftStickPress;
                    @RightStickMove.started += instance.OnRightStickMove;
                    @RightStickMove.performed += instance.OnRightStickMove;
                    @RightStickMove.canceled += instance.OnRightStickMove;
                    @RightStickPress.started += instance.OnRightStickPress;
                    @RightStickPress.performed += instance.OnRightStickPress;
                    @RightStickPress.canceled += instance.OnRightStickPress;
                    @DPadMove.started += instance.OnDPadMove;
                    @DPadMove.performed += instance.OnDPadMove;
                    @DPadMove.canceled += instance.OnDPadMove;
                    @Start.started += instance.OnStart;
                    @Start.performed += instance.OnStart;
                    @Start.canceled += instance.OnStart;
                    @Select.started += instance.OnSelect;
                    @Select.performed += instance.OnSelect;
                    @Select.canceled += instance.OnSelect;
                    @LeftTrigger.started += instance.OnLeftTrigger;
                    @LeftTrigger.performed += instance.OnLeftTrigger;
                    @LeftTrigger.canceled += instance.OnLeftTrigger;
                    @RightTrigger.started += instance.OnRightTrigger;
                    @RightTrigger.performed += instance.OnRightTrigger;
                    @RightTrigger.canceled += instance.OnRightTrigger;
                    @LeftShoulder.started += instance.OnLeftShoulder;
                    @LeftShoulder.performed += instance.OnLeftShoulder;
                    @LeftShoulder.canceled += instance.OnLeftShoulder;
                    @RightShoulder.started += instance.OnRightShoulder;
                    @RightShoulder.performed += instance.OnRightShoulder;
                    @RightShoulder.canceled += instance.OnRightShoulder;
                }
            }
        }
        public MenuActions @Menu => new MenuActions(this);

        // Player
        private readonly InputActionMap m_Player;
        private IPlayerActions m_PlayerActionsCallbackInterface;
        private readonly InputAction m_Player_North;
        private readonly InputAction m_Player_East;
        private readonly InputAction m_Player_South;
        private readonly InputAction m_Player_West;
        private readonly InputAction m_Player_LeftStickMove;
        private readonly InputAction m_Player_LeftStickPress;
        private readonly InputAction m_Player_RightStickMove;
        private readonly InputAction m_Player_RightStickPress;
        private readonly InputAction m_Player_DPadMove;
        private readonly InputAction m_Player_Start;
        private readonly InputAction m_Player_Select;
        private readonly InputAction m_Player_LeftTrigger;
        private readonly InputAction m_Player_RightTrigger;
        private readonly InputAction m_Player_LeftShoulder;
        private readonly InputAction m_Player_RightShoulder;
        public struct PlayerActions
        {
            private @InputActions m_Wrapper;
            public PlayerActions(@InputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @North => m_Wrapper.m_Player_North;
            public InputAction @East => m_Wrapper.m_Player_East;
            public InputAction @South => m_Wrapper.m_Player_South;
            public InputAction @West => m_Wrapper.m_Player_West;
            public InputAction @LeftStickMove => m_Wrapper.m_Player_LeftStickMove;
            public InputAction @LeftStickPress => m_Wrapper.m_Player_LeftStickPress;
            public InputAction @RightStickMove => m_Wrapper.m_Player_RightStickMove;
            public InputAction @RightStickPress => m_Wrapper.m_Player_RightStickPress;
            public InputAction @DPadMove => m_Wrapper.m_Player_DPadMove;
            public InputAction @Start => m_Wrapper.m_Player_Start;
            public InputAction @Select => m_Wrapper.m_Player_Select;
            public InputAction @LeftTrigger => m_Wrapper.m_Player_LeftTrigger;
            public InputAction @RightTrigger => m_Wrapper.m_Player_RightTrigger;
            public InputAction @LeftShoulder => m_Wrapper.m_Player_LeftShoulder;
            public InputAction @RightShoulder => m_Wrapper.m_Player_RightShoulder;
            public InputActionMap Get() { return m_Wrapper.m_Player; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
            public void SetCallbacks(IPlayerActions instance)
            {
                if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
                {
                    @North.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnNorth;
                    @North.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnNorth;
                    @North.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnNorth;
                    @East.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnEast;
                    @East.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnEast;
                    @East.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnEast;
                    @South.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSouth;
                    @South.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSouth;
                    @South.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSouth;
                    @West.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnWest;
                    @West.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnWest;
                    @West.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnWest;
                    @LeftStickMove.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeftStickMove;
                    @LeftStickMove.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeftStickMove;
                    @LeftStickMove.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeftStickMove;
                    @LeftStickPress.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeftStickPress;
                    @LeftStickPress.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeftStickPress;
                    @LeftStickPress.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeftStickPress;
                    @RightStickMove.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRightStickMove;
                    @RightStickMove.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRightStickMove;
                    @RightStickMove.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRightStickMove;
                    @RightStickPress.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRightStickPress;
                    @RightStickPress.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRightStickPress;
                    @RightStickPress.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRightStickPress;
                    @DPadMove.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDPadMove;
                    @DPadMove.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDPadMove;
                    @DPadMove.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDPadMove;
                    @Start.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnStart;
                    @Start.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnStart;
                    @Start.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnStart;
                    @Select.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelect;
                    @Select.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelect;
                    @Select.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelect;
                    @LeftTrigger.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeftTrigger;
                    @LeftTrigger.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeftTrigger;
                    @LeftTrigger.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeftTrigger;
                    @RightTrigger.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRightTrigger;
                    @RightTrigger.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRightTrigger;
                    @RightTrigger.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRightTrigger;
                    @LeftShoulder.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeftShoulder;
                    @LeftShoulder.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeftShoulder;
                    @LeftShoulder.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeftShoulder;
                    @RightShoulder.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRightShoulder;
                    @RightShoulder.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRightShoulder;
                    @RightShoulder.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRightShoulder;
                }
                m_Wrapper.m_PlayerActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @North.started += instance.OnNorth;
                    @North.performed += instance.OnNorth;
                    @North.canceled += instance.OnNorth;
                    @East.started += instance.OnEast;
                    @East.performed += instance.OnEast;
                    @East.canceled += instance.OnEast;
                    @South.started += instance.OnSouth;
                    @South.performed += instance.OnSouth;
                    @South.canceled += instance.OnSouth;
                    @West.started += instance.OnWest;
                    @West.performed += instance.OnWest;
                    @West.canceled += instance.OnWest;
                    @LeftStickMove.started += instance.OnLeftStickMove;
                    @LeftStickMove.performed += instance.OnLeftStickMove;
                    @LeftStickMove.canceled += instance.OnLeftStickMove;
                    @LeftStickPress.started += instance.OnLeftStickPress;
                    @LeftStickPress.performed += instance.OnLeftStickPress;
                    @LeftStickPress.canceled += instance.OnLeftStickPress;
                    @RightStickMove.started += instance.OnRightStickMove;
                    @RightStickMove.performed += instance.OnRightStickMove;
                    @RightStickMove.canceled += instance.OnRightStickMove;
                    @RightStickPress.started += instance.OnRightStickPress;
                    @RightStickPress.performed += instance.OnRightStickPress;
                    @RightStickPress.canceled += instance.OnRightStickPress;
                    @DPadMove.started += instance.OnDPadMove;
                    @DPadMove.performed += instance.OnDPadMove;
                    @DPadMove.canceled += instance.OnDPadMove;
                    @Start.started += instance.OnStart;
                    @Start.performed += instance.OnStart;
                    @Start.canceled += instance.OnStart;
                    @Select.started += instance.OnSelect;
                    @Select.performed += instance.OnSelect;
                    @Select.canceled += instance.OnSelect;
                    @LeftTrigger.started += instance.OnLeftTrigger;
                    @LeftTrigger.performed += instance.OnLeftTrigger;
                    @LeftTrigger.canceled += instance.OnLeftTrigger;
                    @RightTrigger.started += instance.OnRightTrigger;
                    @RightTrigger.performed += instance.OnRightTrigger;
                    @RightTrigger.canceled += instance.OnRightTrigger;
                    @LeftShoulder.started += instance.OnLeftShoulder;
                    @LeftShoulder.performed += instance.OnLeftShoulder;
                    @LeftShoulder.canceled += instance.OnLeftShoulder;
                    @RightShoulder.started += instance.OnRightShoulder;
                    @RightShoulder.performed += instance.OnRightShoulder;
                    @RightShoulder.canceled += instance.OnRightShoulder;
                }
            }
        }
        public PlayerActions @Player => new PlayerActions(this);
        public interface IMenuActions
        {
            void OnNorth(InputAction.CallbackContext context);
            void OnEast(InputAction.CallbackContext context);
            void OnSouth(InputAction.CallbackContext context);
            void OnWest(InputAction.CallbackContext context);
            void OnLeftStickMove(InputAction.CallbackContext context);
            void OnLeftStickPress(InputAction.CallbackContext context);
            void OnRightStickMove(InputAction.CallbackContext context);
            void OnRightStickPress(InputAction.CallbackContext context);
            void OnDPadMove(InputAction.CallbackContext context);
            void OnStart(InputAction.CallbackContext context);
            void OnSelect(InputAction.CallbackContext context);
            void OnLeftTrigger(InputAction.CallbackContext context);
            void OnRightTrigger(InputAction.CallbackContext context);
            void OnLeftShoulder(InputAction.CallbackContext context);
            void OnRightShoulder(InputAction.CallbackContext context);
        }
        public interface IPlayerActions
        {
            void OnNorth(InputAction.CallbackContext context);
            void OnEast(InputAction.CallbackContext context);
            void OnSouth(InputAction.CallbackContext context);
            void OnWest(InputAction.CallbackContext context);
            void OnLeftStickMove(InputAction.CallbackContext context);
            void OnLeftStickPress(InputAction.CallbackContext context);
            void OnRightStickMove(InputAction.CallbackContext context);
            void OnRightStickPress(InputAction.CallbackContext context);
            void OnDPadMove(InputAction.CallbackContext context);
            void OnStart(InputAction.CallbackContext context);
            void OnSelect(InputAction.CallbackContext context);
            void OnLeftTrigger(InputAction.CallbackContext context);
            void OnRightTrigger(InputAction.CallbackContext context);
            void OnLeftShoulder(InputAction.CallbackContext context);
            void OnRightShoulder(InputAction.CallbackContext context);
        }
    }
}
